after_success: coveralls
dist: trusty
install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      brew update
      brew install python3
      brew install openssl@1.1
      export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
      export CFLAGS="-I$(brew --prefix openssl@1.1)/include"
      python3 -m venv env
      source env/bin/activate
    fi
  - pip install aioice coveralls flake8
  - pip install -e git://github.com/pyca/cryptography.git@a36579b6e4086ded4c20578bbfbfae083d5e6bce#egg=cryptography
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
script:
  - flake8 aiowebrtc tests
  - coverage run setup.py test
