addons:
  apt:
    packages:
    - libopus-dev
    - libvpx-dev
after_success: coveralls
cache: pip
dist: trusty
install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      brew update
      brew upgrade python3
      brew install opus libvpx
    fi
  - pip3 install -U setuptools
  - pip3 install coveralls flake8
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
script:
  - flake8 aiortc examples tests
  - coverage run setup.py test
