after_success: coveralls
dist: trusty
install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      brew update
      brew upgrade openssl@1.1
      brew install python3 srtp
      export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
      export CFLAGS="-I$(brew --prefix openssl@1.1)/include"
      python3 -m venv env
      source env/bin/activate
    else
      .travis/build-libsrtp
      export LD_LIBRARY_PATH=$PWD/libsrtp:$LD_LIBRARY_PATH
    fi
  - pip install coveralls flake8
  - pip install -e git://github.com/pyca/cryptography.git@a36579b6e4086ded4c20578bbfbfae083d5e6bce#egg=cryptography
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "pypy3"
script:
  - flake8 aiortc examples tests
  - coverage run setup.py test
