addons:
  apt:
    packages:
    - libavdevice-dev
    - libavfilter-dev
    - libopus-dev
    - libvpx-dev
cache: pip
dist: xenial
install: .travis/install
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - env: BUILD=sdist
    python: "3.6"
script: .travis/script
sudo: true
