addons:
  apt:
    packages:
    - libopus-dev
    - libvpx-dev
after_success: coveralls
cache: pip
dist: trusty
install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      brew update
      brew upgrade python3
      brew install opus libvpx
    fi
  - pip3 install -U setuptools
  - pip3 install coveralls flake8
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - env: BUILD=sdist
    python: "3.6"
script:
  - |
    if [ "$BUILD" = "sdist" ]; then
      python3 setup.py sdist
      if [ -n "$TRAVIS_TAG" ]; then
        pip3 install twine
        python3 -m twine upload --skip-existing dist/*
      fi
    else
      flake8 aiortc examples tests
      coverage run setup.py test
    fi
